[package]
name = "opening_hours_parser"
version = "0.1.0"
edition = "2021"

[lib]
name = "opening_hours_parser"
crate-type = [ "cdylib" ]

[profile.dev]
lto = "fat"

[profile.release]
lto = "fat"

[dependencies]
chrono = "0.4.41"
opening-hours = "1.1.3"
